name: konsulta_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  url_strategy: ^0.3.0
  go_router:
  jwt_decoder: ^2.0.1
  flutter_typeahead: ^5.2.0
  material_symbols_icons: ^4.2874.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  http: ^1.2.2
  get_it: ^8.2.0
  injectable: ^2.4.1
  flutter_secure_storage: ^9.2.4
  data_table_2: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - assets/icons/
